import React, { useState } from 'react';
import { ArrowLeft, CheckCircle, XCircle, FileText, Users, Clock, MessageSquare, Sparkles, Download, RefreshCw, TrendingUp, AlertTriangle, Plus } from 'lucide-react';

interface ConclusionPageProps {
  onBack: () => void;
  analysisResult: AnalysisResult | null;
  topic: string;
  participants: number;
  duration: number;
  hasConclusion: boolean;
  onExtendTime?: (additionalMinutes: number) => void;
}

interface AnalysisResult {
  summary: string;
  keyPoints: string[];
  commonThemes: string[];
  conclusions: string[];
  sentiment: string;
  participationAnalysis: string;
}

export default function ConclusionPage({ 
  onBack, 
  analysisResult, 
  topic, 
  participants, 
  duration, 
  hasConclusion,
  onExtendTime 
}: ConclusionPageProps) {
  
  const [showExtendOptions, setShowExtendOptions] = useState(false);
  const [customTime, setCustomTime] = useState('');

  const downloadReport = () => {
    if (analysisResult) {
      const reportText = `
Option.ai Discussion Conclusion Report
=====================================

Discussion Topic: ${topic}
Participants: ${participants} people
Duration: ${duration} minutes
Analysis Time: ${new Date().toLocaleString()}
Conclusion Status: ${hasConclusion ? 'Consensus Reached' : 'No Clear Consensus Reached'}

${hasConclusion ? `
✅ Discussion Conclusions
------------------------
${analysisResult.conclusions.map(conclusion => `• ${conclusion}`).join('\n')}

📋 Key Points
-------------
${analysisResult.keyPoints.map(point => `• ${point}`).join('\n')}

🎯 Common Themes
---------------
${analysisResult.commonThemes.map(theme => `• ${theme}`).join('\n')}
` : `
❌ Discussion Analysis
---------------------
This discussion did not reach a clear consensus or conclusion.

Possible Reasons:
• Insufficient discussion time, requiring more in-depth exploration
• Significant divergence of opinions among participants
• High complexity of the topic, requiring phased discussion
• Lack of sufficient background information or data support

Recommended Follow-up Actions:
• Schedule follow-up discussion meetings
• Collect more relevant information and data
• Invite relevant experts to participate in discussions
• Break down complex topics into smaller sub-topics
`}

💭 Discussion Summary
--------------------
${analysisResult.summary}

😊 Sentiment Analysis
--------------------
${analysisResult.sentiment}

👥 Participation Analysis
------------------------
${analysisResult.participationAnalysis}

---
Generated by Option.ai AI Discussion Platform
      `;

      const blob = new Blob([reportText], { type: 'text/plain;charset=utf-8' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `discussion-conclusion-report-${Date.now()}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    }
  };

  const restartDiscussion = () => {
    // Logic to restart discussion
    onBack();
  };

  const handleExtendTime = (minutes: number) => {
    if (onExtendTime) {
      onExtendTime(minutes);
    }
  };

  const handleCustomExtend = () => {
    const minutes = parseInt(customTime);
    if (!isNaN(minutes) && minutes > 0) {
      handleExtendTime(minutes);
      setCustomTime('');
      setShowExtendOptions(false);
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-blue-900 to-indigo-900 relative overflow-hidden">
      {/* Background Elements */}
      <div className="absolute inset-0">
        <div className="absolute top-20 left-20 w-72 h-72 bg-blue-500/10 rounded-full blur-3xl animate-pulse"></div>
        <div className="absolute bottom-20 right-20 w-96 h-96 bg-purple-500/10 rounded-full blur-3xl animate-pulse delay-1000"></div>
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] bg-gradient-radial from-blue-500/5 to-transparent rounded-full"></div>
      </div>

      {/* Header */}
      <header className="relative z-10 bg-white/5 backdrop-blur-lg border-b border-white/10">
        <div className="max-w-7xl mx-auto px-6 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-4">
              <button
                onClick={onBack}
                className="p-2 hover:bg-white/10 rounded-lg transition-colors"
              >
                <ArrowLeft className="w-6 h-6 text-white" />
              </button>
              <div className="flex items-center space-x-3">
                <img 
                  src="/ChatGPT Image 2025年6月7日 上午11_04_52 copy copy.png" 
                  alt="Option.ai Logo" 
                  className="w-10 h-10 object-contain"
                />
                <div>
                  <h1 className="text-xl font-bold text-white">Option.ai</h1>
                  <p className="text-xs text-blue-200 opacity-80">Discussion Conclusion</p>
                </div>
              </div>
            </div>

            {/* Meeting Info */}
            <div className="flex items-center space-x-6 text-white/80">
              <div className="flex items-center space-x-2">
                <Users className="w-4 h-4" />
                <span className="text-sm">{participants} participants</span>
              </div>
              <div className="flex items-center space-x-2">
                <Clock className="w-4 h-4" />
                <span className="text-sm">{duration} minutes</span>
              </div>
            </div>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="relative z-10 flex-1 px-6 py-8">
        <div className="max-w-4xl mx-auto">
          
          {/* Status Header */}
          <div className="text-center mb-8">
            <div className={`inline-flex items-center space-x-4 backdrop-blur-lg border rounded-2xl p-6 ${
              hasConclusion 
                ? 'bg-green-500/10 border-green-400/30' 
                : 'bg-red-500/10 border-red-400/30'
            }`}>
              {hasConclusion ? (
                <CheckCircle className="w-12 h-12 text-green-400" />
              ) : (
                <XCircle className="w-12 h-12 text-red-400" />
              )}
              <div className="text-left">
                <h2 className={`text-3xl font-bold mb-2 ${
                  hasConclusion ? 'text-green-300' : 'text-red-300'
                }`}>
                  {hasConclusion ? '✅ Discussion Reached Consensus' : '❌ Discussion Did Not Reach Clear Conclusion'}
                </h2>
                <p className="text-white/70 text-lg">
                  {hasConclusion 
                    ? 'Congratulations! Your team successfully reached a discussion consensus' 
                    : 'The discussion requires more time or further exploration'
                  }
                </p>
              </div>
            </div>
          </div>

          {/* Topic Display */}
          <div className="bg-white/10 backdrop-blur-lg border border-white/20 rounded-2xl p-6 mb-8">
            <div className="flex items-center space-x-3 mb-4">
              <MessageSquare className="w-6 h-6 text-blue-300" />
              <h3 className="text-xl font-bold text-white">Discussion Topic</h3>
            </div>
            <p className="text-white/80 text-lg bg-white/5 rounded-lg p-4">{topic}</p>
          </div>

          {hasConclusion ? (
            /* With Conclusion */
            <div className="space-y-8">
              {/* Main Conclusions */}
              <div className="bg-gradient-to-r from-green-500/10 to-emerald-500/10 backdrop-blur-lg border border-green-400/30 rounded-2xl p-8">
                <div className="flex items-center space-x-3 mb-6">
                  <TrendingUp className="w-8 h-8 text-green-400" />
                  <h3 className="text-2xl font-bold text-white">🎯 Discussion Conclusions</h3>
                </div>
                <div className="space-y-4">
                  {analysisResult?.conclusions.map((conclusion, index) => (
                    <div key={index} className="bg-white/10 rounded-lg p-4 flex items-start space-x-3">
                      <div className="w-8 h-8 bg-green-500/20 rounded-full flex items-center justify-center flex-shrink-0 mt-1">
                        <span className="text-green-300 font-bold text-sm">{index + 1}</span>
                      </div>
                      <p className="text-white/90 leading-relaxed">{conclusion}</p>
                    </div>
                  ))}
                </div>
              </div>

              {/* Key Points */}
              <div className="bg-white/10 backdrop-blur-lg border border-white/20 rounded-2xl p-8">
                <div className="flex items-center space-x-3 mb-6">
                  <Sparkles className="w-6 h-6 text-blue-300" />
                  <h3 className="text-xl font-bold text-white">💡 Key Discussion Points</h3>
                </div>
                <div className="grid gap-3">
                  {analysisResult?.keyPoints.map((point, index) => (
                    <div key={index} className="bg-white/5 rounded-lg p-4 flex items-start space-x-3">
                      <div className="w-2 h-2 bg-blue-400 rounded-full mt-3 flex-shrink-0"></div>
                      <p className="text-white/80">{point}</p>
                    </div>
                  ))}
                </div>
              </div>

              {/* Common Themes */}
              <div className="bg-white/10 backdrop-blur-lg border border-white/20 rounded-2xl p-8">
                <div className="flex items-center space-x-3 mb-6">
                  <Users className="w-6 h-6 text-purple-300" />
                  <h3 className="text-xl font-bold text-white">🤝 Common Focus Areas</h3>
                </div>
                <div className="flex flex-wrap gap-3">
                  {analysisResult?.commonThemes.map((theme, index) => (
                    <div key={index} className="bg-purple-500/20 border border-purple-400/30 rounded-full px-4 py-2">
                      <span className="text-purple-200 font-medium">{theme}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          ) : (
            /* Without Conclusion */
            <div className="space-y-8">
              {/* Extend Time Options */}
              <div className="bg-gradient-to-r from-orange-500/10 to-yellow-500/10 backdrop-blur-lg border border-orange-400/30 rounded-2xl p-8">
                <div className="flex items-center space-x-3 mb-6">
                  <Clock className="w-8 h-8 text-orange-400" />
                  <h3 className="text-2xl font-bold text-white">⏰ Extend Discussion Time</h3>
                </div>
                <p className="text-white/80 mb-6 text-lg">
                  Since no clear conclusion was reached, you can extend the discussion time to allow for deeper exploration of the topic.
                </p>
                
                {!showExtendOptions ? (
                  <button
                    onClick={() => setShowExtendOptions(true)}
                    className="bg-orange-500 hover:bg-orange-600 text-white px-8 py-4 rounded-xl font-semibold flex items-center space-x-3 transition-all duration-200 transform hover:scale-105 shadow-lg"
                  >
                    <Plus className="w-6 h-6" />
                    <span>Add More Discussion Time</span>
                  </button>
                ) : (
                  <div className="space-y-6">
                    <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                      {[5, 10, 15, 30].map((minutes) => (
                        <button
                          key={minutes}
                          onClick={() => handleExtendTime(minutes)}
                          className="bg-orange-500/20 hover:bg-orange-500/30 border border-orange-400/50 rounded-xl p-4 text-center transition-all duration-200 transform hover:scale-105"
                        >
                          <div className="text-2xl font-bold text-orange-300 mb-1">+{minutes}</div>
                          <div className="text-sm text-white/70">minutes</div>
                        </button>
                      ))}
                    </div>
                    
                    <div className="bg-white/10 rounded-lg p-4">
                      <label className="block text-white font-medium mb-3">Custom Time Extension:</label>
                      <div className="flex items-center space-x-3">
                        <input
                          type="number"
                          min="1"
                          max="120"
                          value={customTime}
                          onChange={(e) => setCustomTime(e.target.value)}
                          placeholder="Enter minutes"
                          className="flex-1 bg-white/10 border border-white/20 rounded-lg px-4 py-3 text-white placeholder-white/50 focus:outline-none focus:border-orange-400 focus:ring-2 focus:ring-orange-400/20"
                        />
                        <button
                          onClick={handleCustomExtend}
                          disabled={!customTime || parseInt(customTime) <= 0}
                          className="bg-orange-500 hover:bg-orange-600 disabled:opacity-50 disabled:cursor-not-allowed text-white px-6 py-3 rounded-lg font-medium transition-colors"
                        >
                          Extend
                        </button>
                      </div>
                    </div>
                    
                    <button
                      onClick={() => setShowExtendOptions(false)}
                      className="text-white/60 hover:text-white transition-colors text-sm"
                    >
                      Cancel
                    </button>
                  </div>
                )}
              </div>

              {/* Analysis Explanation */}
              <div className="bg-gradient-to-r from-red-500/10 to-orange-500/10 backdrop-blur-lg border border-red-400/30 rounded-2xl p-8">
                <div className="flex items-center space-x-3 mb-6">
                  <AlertTriangle className="w-8 h-8 text-red-400" />
                  <h3 className="text-2xl font-bold text-white">📊 Discussion Analysis Results</h3>
                </div>
                <div className="bg-white/10 rounded-lg p-6">
                  <p className="text-white/90 leading-relaxed text-lg mb-4">
                    According to AI analysis, this discussion did not reach a clear consensus or conclusion. This may be due to the following reasons:
                  </p>
                  <ul className="space-y-3 text-white/80">
                    <li className="flex items-start space-x-3">
                      <div className="w-2 h-2 bg-red-400 rounded-full mt-3 flex-shrink-0"></div>
                      <span>Insufficient discussion time, topic requires deeper exploration</span>
                    </li>
                    <li className="flex items-start space-x-3">
                      <div className="w-2 h-2 bg-red-400 rounded-full mt-3 flex-shrink-0"></div>
                      <span>Significant divergence of opinions among participants</span>
                    </li>
                    <li className="flex items-start space-x-3">
                      <div className="w-2 h-2 bg-red-400 rounded-full mt-3 flex-shrink-0"></div>
                      <span>High topic complexity requiring phased handling</span>
                    </li>
                    <li className="flex items-start space-x-3">
                      <div className="w-2 h-2 bg-red-400 rounded-full mt-3 flex-shrink-0"></div>
                      <span>Lack of sufficient background information or data support</span>
                    </li>
                  </ul>
                </div>
              </div>

              {/* Recommended Actions */}
              <div className="bg-white/10 backdrop-blur-lg border border-white/20 rounded-2xl p-8">
                <div className="flex items-center space-x-3 mb-6">
                  <TrendingUp className="w-6 h-6 text-yellow-300" />
                  <h3 className="text-xl font-bold text-white">💡 Recommended Follow-up Actions</h3>
                </div>
                <div className="grid gap-4">
                  <div className="bg-yellow-500/10 border border-yellow-400/30 rounded-lg p-4">
                    <h4 className="text-yellow-300 font-semibold mb-2">🔄 Schedule Follow-up Discussion</h4>
                    <p className="text-white/80">Recommend scheduling longer follow-up meetings to allow participants sufficient time to express their views</p>
                  </div>
                  <div className="bg-blue-500/10 border border-blue-400/30 rounded-lg p-4">
                    <h4 className="text-blue-300 font-semibold mb-2">📚 Gather More Information</h4>
                    <p className="text-white/80">Before the next discussion, collect relevant data, case studies, or expert opinions</p>
                  </div>
                  <div className="bg-purple-500/10 border border-purple-400/30 rounded-lg p-4">
                    <h4 className="text-purple-300 font-semibold mb-2">👨‍💼 Invite Expert Participation</h4>
                    <p className="text-white/80">Consider inviting experts or stakeholders from relevant fields to participate in the discussion</p>
                  </div>
                  <div className="bg-green-500/10 border border-green-400/30 rounded-lg p-4">
                    <h4 className="text-green-300 font-semibold mb-2">🔍 Break Down Topics</h4>
                    <p className="text-white/80">Break complex topics into smaller, more specific sub-topics for discussion</p>
                  </div>
                </div>
              </div>

              {/* Discussion Summary */}
              {analysisResult && (
                <div className="bg-white/10 backdrop-blur-lg border border-white/20 rounded-2xl p-8">
                  <div className="flex items-center space-x-3 mb-6">
                    <FileText className="w-6 h-6 text-gray-300" />
                    <h3 className="text-xl font-bold text-white">📝 Discussion Summary</h3>
                  </div>
                  <div className="bg-white/5 rounded-lg p-6">
                    <p className="text-white/80 leading-relaxed">{analysisResult.summary}</p>
                  </div>
                </div>
              )}
            </div>
          )}

          {/* Action Buttons */}
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4 mt-12">
            <button
              onClick={downloadReport}
              className="bg-blue-500 hover:bg-blue-600 text-white px-8 py-4 rounded-xl font-semibold flex items-center space-x-3 transition-all duration-200 transform hover:scale-105 shadow-lg min-w-[200px]"
            >
              <Download className="w-6 h-6" />
              <span>Download Full Report</span>
            </button>
            
            <button
              onClick={restartDiscussion}
              className="bg-gradient-to-r from-purple-500 to-indigo-600 hover:from-purple-600 hover:to-indigo-700 text-white px-8 py-4 rounded-xl font-semibold flex items-center space-x-3 transition-all duration-200 transform hover:scale-105 shadow-lg min-w-[200px]"
            >
              <RefreshCw className="w-6 h-6" />
              <span>{hasConclusion ? 'Start New Discussion' : 'Restart Discussion'}</span>
            </button>
          </div>

          {/* Additional Information */}
          {analysisResult && (
            <div className="grid md:grid-cols-2 gap-6 mt-8">
              <div className="bg-white/5 backdrop-blur-sm border border-white/10 rounded-xl p-6">
                <h4 className="text-lg font-semibold text-white mb-3 flex items-center space-x-2">
                  <Sparkles className="w-5 h-5 text-blue-300" />
                  <span>Sentiment Analysis</span>
                </h4>
                <p className="text-white/80">{analysisResult.sentiment}</p>
              </div>
              
              <div className="bg-white/5 backdrop-blur-sm border border-white/10 rounded-xl p-6">
                <h4 className="text-lg font-semibold text-white mb-3 flex items-center space-x-2">
                  <Users className="w-5 h-5 text-green-300" />
                  <span>Participation Analysis</span>
                </h4>
                <p className="text-white/80">{analysisResult.participationAnalysis}</p>
              </div>
            </div>
          )}
        </div>
      </main>
    </div>
  );
}